#!/usr/bin/env python3
"""Fake rsync: copies `src user@host:dest` locally. Hosts in $FAKE_SSH_DOWN are unreachable.

FAKE_RSYNC_CORRUPT=1 writes a truncated copy, to exercise verification.
"""

import json
import os
import shutil
import sys

args = sys.argv[1:]
src, dest = args[-2], args[-1]
target, path = dest.split(":", 1)
host = target.split("@", 1)[-1]
with open(os.environ["FAKE_LOG"], "a") as fh:
    fh.write(json.dumps({"tool": "rsync", "host": host, "args": args}) + "\n")
if host in os.environ.get("FAKE_SSH_DOWN", "").split(","):
    sys.exit(255)
if os.environ.get("FAKE_RSYNC_CORRUPT"):
    with open(src, "rb") as source, open(path, "wb") as copy:
        copy.write(source.read()[:-10])
else:
    shutil.copyfile(src, path)
