#!/usr/bin/env python3
"""Fake audio player that records its call to $FAKE_LOG and keeps "playing" for a minute."""

import json
import os
import sys
import time

with open(os.environ["FAKE_LOG"], "a") as fh:
    fh.write(json.dumps({"tool": "slow-player", "args": sys.argv[1:], "pid": os.getpid()}) + "\n")
time.sleep(60)
