#!/usr/bin/env python3
"""Fake ssh: runs the remote command locally. Hosts in $FAKE_SSH_DOWN are unreachable."""

import json
import os
import subprocess
import sys

args = sys.argv[1:]
while args and args[0] == "-o":
    args = args[2:]
target, command = args[0], args[1:]
host = target.split("@", 1)[-1]
with open(os.environ["FAKE_LOG"], "a") as fh:
    fh.write(json.dumps({"tool": "ssh", "host": host, "args": command}) + "\n")
if host in os.environ.get("FAKE_SSH_DOWN", "").split(","):
    print(f"ssh: connect to host {host}: No route to host", file=sys.stderr)
    sys.exit(255)
sys.exit(subprocess.run(["sh", "-c", " ".join(command)]).returncode)
